### create article
POST localhost:8081/article/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODI0NTQsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3NDY4ODU0LCJpc3MiOiJLdW5VelRlc3QifQ.AynSIPa4dDVZd07sTUjPxXiG_Xabh0mP4gU1L57spYY8sHV7MQGQtgN-boD8s4goO3qNjZM9LW5QZ35mSK8a8Q

{
  "title": "Германияда иш ўринлари, ўқитувчилар ҳақида қонун ва сотилган Magic City — ҳафта дайжести",
  "description": "Германия ўзбекистонликлар учун 50 мингта иш ўрнини таклиф қилмоқда. Ватандошларимиз энди Қозоғистонда 1 ой регистрациядан ўтмай яшаши мумкин",
  "content": "Ўзбекистон фуқароларининг Қозоғистон ҳудудида рўйхатдан ўтмасдан бўлиб туриш муддати 5 кундан 30 кунга узайтирилди. Худди шундай тартиб Ўзбекистонга келган қозоғистонликлар учун ҳам амал қилади. Шу билан бирга, фуқароларнинг қўшни мамлакатда вақтинча бўлиб туриш муддати 6 ой давомида жами 90 кундан ошмаслиги керак. Бу ҳақдаги келишувни 31 январ куни Қозоғистон парламенти тасдиқлади.",
  "regionId": 1,
  "categoryId": 1,
  "imageId": "3243dc92-0808-4730-aaa7-4829b99e190b",
  "article type": [
    1,
    2
  ],
  "photoId": "e8aaa3ca-f15c-46f8-a7f3-52be248e278f"
}

### delete article
PUT localhost:8081/article/adm/delete/dc5d523a-d930-4408-a9ad-f473af147948
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMDgwMDAsImlkIjoxOSwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzI5NDQwMCwiaXNzIjoiS3VuVXpUZXN0In0.7ihVbIHVxBbwoo3FEvvEbiUpCF0rq_OVltJYjkhmNoGS1fTl9qzvSWFYfeerIIsTXCq8gS_tKTH0M48H9TQQ4Q

### change status article
PUT localhost:8081/article/adm/change_status/c1599dab-15c6-468f-a031-a99ebf930914/status?status=NotPublished
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODM5MTQsImlkIjoyLCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNzA3NDcwMzE0LCJpc3MiOiJLdW5VelRlc3QifQ.PSP6eTXfEk3pj4KmCa2Z6v9IAU91Ox48LsXGuWZuyPco51XXctFCkVj3yykLAlYBuZwnd8JroKbDB-dN38JPJw

### Get Last 5 Article By Types
GET localhost:8081/article/typeList


