### create article type
POST localhost:8081/articleType/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY2MDY0OTAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2OTI4OTAsImlzcyI6Ikt1blV6VGVzdCJ9.XkEyhGCH_VUdfivc0IUmfqzlUhaYIUPRb8rtfFS63EL2kBM0vPDpltjKX51fPAalfh18BppxTS5m1Yw8wMDg8Q

{
  "order_number": 1,
  "name_uz": "Maqola",
  "name_ru": "статья",
  "name_en": "Article"
}


### update
PUT localhost:8081/articleType/update/1
Content-Type: application/json

{
  "order_number": 2,
  "name_uz": "sinov",
  "name_ru": "тест",
  "name_en": "test"
}

### delete
DELETE localhost:8081/articleType/delete/1

### get all paginations
GET localhost:8081/articleType/all?page=1&size=10

### getByLang
GET localhost:8081/articleType/lang?lang=en

