### login
POST localhost:8081/auth/login
Content-Type: application/json

{
  "email": "DdD@gmail.com",
  "password": ""
}

###
POST localhost:8081/auth/registrationSms
Content-Type:application/json

{
  "name": "Ahaha",
  "surname": "vali",
  "email": "jamol3904@gmail.com",
  "password": "12",
  "phone": "998337200219"
}


###
POST localhost:8081/auth/registration
ConteyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcxMTA4MTQsImlkIjoxOSwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzE5NzIxNCwiaXNzIjoiS3VuVXpUZXN0In0.Kj7Um4wjmPkEGRRkvHJupJEGYubOcxAgra4a0wcoS9ZEUxTHxQ4gglzMJRtqpJvWrIpqfkkTI4QwZCvdD5DIuQent-Type:application/json

{
  "name": "Ahaha",
  "surname": "vali",
  "email": "jamol3904@gmail.com",
  "password": "12",
  "phone": "9983327001"
}