### craeate category
POST localhost:8081/category/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MDcwNTMsImVtYWlsIjoidWNoYW5hbDEwQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3ODkzNDUzLCJpc3MiOiJLdW5VelRlc3QifQ.UMs1fczJuuHbM39YRoFw-MP_a3G5aXgsBzA3yd-Wt3fwZ6wTPiIvqtM8elxwp4CanNsTDCpEdYjUP-CYZSHPTA

{
  "order_number": 1,
  "name_uz": "Jahon",
  "name_ru": "Mir ru",
  "name_en": "world"
}

### get all
GET localhost:8081/category/all

### getByLang
GET localhost:8081/category/lang?lang=en
Content-Type: application/json