### craeate category
POST localhost:8081/category/create
Content-Type: application/json


{
  "order_number": 1,
  "name_uz": "test",
  "name_ru": "te",
  "name_en": "st"
}

### get all
GET localhost:8081/category/all
