### init admin
GET localhost:8081/admin/initAdmin

### create profile
POST localhost:8081/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODk2NjYsImVtYWlsIjoidWNoYW5hbDEwQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MTc2MDY2LCJpc3MiOiJLdW5VelRlc3QifQ.DoZH0ow8bUWsTKb-RWaUetHrhmAmRrZpAvu_whkzYsYoHE1BWPwnhFc-Qvgc8RD-FivIb0U_g5HOAQbKxQUBJw

{
  "name": "Moder",
  "surname": "Aliyev",
  "email": "edD@gmail.com",
  "password": "12345",
  "status": "ACTIVE",
  "role": "ROLE_PUBLISHER"
}

###update user
PUT localhost:8081/profile/updateUser/2
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "haha@gmail.com",
  "password": "0000"
}

###update user
PUT localhost:8081/profile/updateAdmin/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYxMjE4NTUsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyMDgyNTUsImlzcyI6Ikt1blV6VGVzdCJ9.j0fE0SE8WEC1OQ-5crLzUjP5agosZ49xLRrwUcyZZF0R2fY_HdcZt3AuSW-yaPYF7vWOFLYTOwyk3C9RiK2cXw

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "EE@gmail.com",
  "password": "1111"
}

### get allBy paginations
GET localhost:8081/profile/all?page=1&size=10

### filter
POST localhost:8081/profile/filter?pago=1&size=10
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "DD@gmail.com",
  "password": "1234",
  "status": "ACTIVE",
  "role": "ROLE_USER"
}

