### create
POST localhost:8081/region/adm
Content-Type:application/json
Authorization: Basic dXNlcjo3YTZmYTlkYy01YmE1LTQ5ZWItYTdiNi0xMWY2ZDNjODlhYjE=

{
  "order_number": 1,
  "name_uz": "jah",
  "name_ru": "test",
  "name_en": "test"
}


### update By id
PUT localhost:8081/Region/update/1
Content-Type: application/json

{
  "order_number": 1,
  "name_uz": "Toshkent",
  "name_ru": "Ташкент",
  "name_en": "Tashkent"
}

### Delete by id
DELETE localhost:8081/Region/delete/2

### get all
GET localhost:8081/Region/all

### get by lang
GET localhost:8081/Region/lang/en