### create
POST localhost:8081/Region/create
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjY1MjAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI5MjAsImlzcyI6Ikt1blV6VGVzdCJ9.5KWaICurDCb802paHasJ4B4eCxWkNIa12IWcnVd_Ec_hk1IKrObxEiaQiOYy-_N0ELaicscPX22U-dnIoQH6fw

{
  "order_number": 1,
  "name_uz": "test",
  "name_ru": "test",
  "name_en": "test"
}


### update By id
PUT localhost:8081/Region/update/1
Content-Type: application/json

{
  "order_number": 1,
  "name_uz": "Toshkent",
  "name_ru": "Ташкент",
  "name_en": "Tashkent"
}

### Delete by id
DELETE localhost:8081/Region/delete/2

### get all
GET localhost:8081/Region/all

### get by lang
GET localhost:8081/Region/lang/en